apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: coursework
  namespace: production
spec:
  interval: 15m
  chart:
    spec:
      chart: ./charts/prodaction
      version: 0.1.0
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 10m
  releaseName: coursework-prodaction
