apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: coursework
  namespace: staging
spec:
  interval: 15m
  dependsOn:
    - name: coursework-db
      namespace: staging
  chart:
    spec:
      chart: ./charts/staging
      version: 0.1.0
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 10m
  releaseName: coursework-staging
