apiVersion: kustomize.config.k8s.io/v1
kind: Kustomization
metadata:
  name: cnpg-operator
  namespace: flux-system
spec:
  interval: 10m0s
  targetNamespace: cnpg-operator
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: "./cnpg"
  prune: true
  timeout: 1m0s