apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cnpg-operator
  namespace: flux-system
spec:
  interval: 10m0s
  targetNamespace: coursework-ns
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: "./infrastructure/cnpg"
  prune: true
  timeout: 1m0s