apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: coursework
  namespace: flux-system
spec:
  dependsOn:
    - name: name-ns
    - name: dbpg-operator
  interval: 10m0s
  targetNamespace: coursework-ns
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: "./apps/base/appcharts"
  prune: true
  timeout: 1m0s
