apiVersion: kustomize.config.k8s.io/v1
kind: Kustomization
metadata:
  name: coursework
  namespace: flux-system
spec:
  interval: 10m0s
  targetNamespace: coursework-ns
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: "./clusters/coursework"
  prune: true
  timeout: 1m0s