apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: name-ns
  namespace: flux-system
spec:
  sourceRef:
    kind: GitRepository
    name: flux-system
  interval: 10m0s
  path: "./infrastructure/name-ns"
  prune: true
  timeout: 1m0s