apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: dbpg-operator
  namespace: flux-system
spec:
  dependsOn:
    - name: name-ns
  interval: 10m0s
  targetNamespace: coursework-ns
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: "./infrastructure/base"
  prune: true
  timeout: 1m0s